server:
  port: 9098
spring:
  datasource:
    url: jdbc:mysql:///student_dubbo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: StudentService
  registry:
    address: zookeeper://192.168.191.191:2181
  protocol:
    port: -1